services:
  postgres:
    image: postgres:16-alpine
    container_name: pokelike_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pokelike_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5

  battle_engine:
    build:
      context: ./battle_engine
      dockerfile: Dockerfile
    container_name: pokelike_battle_engine
    env_file:
      - ./battle_engine/.env
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/battle_engine_development
      RABBITMQ_URL: amqp://guest:admin@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./battle_engine:/app
    stdin_open: true
    tty: true

  battle_real_time:
    build:
      context: ./battle_real_time
      dockerfile: Dockerfile
      target: dev
    container_name: pokelike_battle_real_time
    env_file:
      - ./battle_real_time/.env
    environment:
      RABBITMQ_URL: amqp://guest:admin@rabbitmq:5672
      MIX_ENV: dev
      PORT: "4000"
    ports:
      - "4000:4000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./battle_real_time:/app
      - battle_real_time_deps:/app/deps
      - battle_real_time_build:/app/_build

volumes:
  postgres_data:
  rabbitmq_data:
  battle_real_time_deps:
  battle_real_time_build:
