name: pixel_clash
description: "¡Prepárate para la batalla! Crea y gestiona tus equipos de monstruos de bolsillo en esta moderna arena de combate online, con una interfaz intuitiva y elegante que te sumerge directamente en la acción."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  phoenix_socket: ^0.8.0
  flutter_svg: ^2.3.0
  shared_preferences: ^2.2.3
  audioplayers: ^6.7.1
  mix: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/types/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
