#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../boot"

migrations_path = File.expand_path("../db/migrate", __dir__)

BattleEngine.logger.info("[DB] Running migrations from #{migrations_path}")

ActiveRecord::MigrationContext.new(migrations_path).migrate

BattleEngine.logger.info("[DB] Migrations complete")
