#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../boot"

migrations_path = File.expand_path("../db/migrate", __dir__)
steps = (ARGV[0] || 1).to_i

BattleEngine.logger.info("[DB] Rolling back #{steps} migration(s)")

ActiveRecord::MigrationContext.new(migrations_path).rollback(steps)

BattleEngine.logger.info("[DB] Rollback complete")
