#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../boot"

BattleEngine.logger.info("[RabbitMQ] Preparing sample message...")

Publishers::BattleEventsPublisher.publish("battle_started", {
  trainer_id: 1,
  opponent_id: 2
})
